// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'privateLabel': string;
  'publicLabel': string;
  'semiPrivateLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
